source "https://rubygems.org"

gem "rest-client"
gem "awesome_print"
gem "json"
gem "rake"
gem "irb"
gem "activesupport", require: "active_support/all"
gem "dotenv", require: "dotenv/tasks"
gem "faraday_middleware"
gem "slack-ruby-client"
gem "byebug"
